# Generated by Django 4.2.4 on 2024-05-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_book',
            field=models.ImageField(default='default_cover.jpg', upload_to=''),
        ),
    ]
